/// `initialize` 응답에 실려 agent 의 context 에 들어가는 server 사용 안내.
///
/// tool 설명에 없는 tool 사이의 순서와 전제만 적는다. 모든 대화에 들어가므로 tool 설명을 반복하지 않는다.
export const serverInstructions = [
  "Unity Play MCP controls a game in Play Mode in the local Unity editor.",
  "Call get_unity_status first. If Unity is not running, ask the user to enter Play Mode instead of retrying.",
  "",
  "Reading the scene:",
  "- Call start_readings once before the first get_scene_state.",
  "- Readings arrive about once a second. After an action, compare reading numbers or call wait_for_condition for a scene or member value.",
  "- A result with stale holds an old reading; do not act on its ids. Call start_readings and read again.",
  "- Narrow large scenes with selector, or use root and depth for a hierarchy.",
  "- Use search_targets to find compact ids/selectors by name, text, component, or actionability, then call get_scene_state.",
  "- Call stop_readings when done.",
  "",
  "Acting on the scene:",
  "- Every tool that aims at something takes the same target: targetId (an instance id from get_scene_state), the exact selector, or x and y. Read state first; never guess an id.",
  "- click, hover, and drag aim at a point and go through the game's own input path (Buttons, pointer handlers, colliders); drag takes from and to. enter_text and capture_screen need an object, so they take targetId or selector, not x and y.",
  "- Otherwise use move_mouse, mouse_button, press_key, set_axis, and set_button.",
  "- perform_actions sends actions together in one frame-aligned batch.",
  "",
  "Playing (observe, decide, act, check):",
  "- get_play_capabilities first; on unsupported_capability keep using the tools above.",
  "- observe gives a fresh snapshot with entity refs and action refs; act_and_observe takes one input with a new operationId and returns execution (input accepted) apart from outcome (effect seen, unknown without expect).",
  "- Missing data is unknown, never success. watch_events waits once for a change.",
  "",
  "Seeing the result:",
  "- capture_screen shows player-visible layout; scene state only reports values.",
  "- pause_game freezes time, resume_game continues, and reset_game starts over.",
].join("\n");
